language: node_js
node_js:
  - 12
services:
  - postgresql
before_script:
  - psql -f db/install.sql -U postgres
  - PGPASSWORD=12345 psql -d bookshop -f db/structure.sql -U danden
  - PGPASSWORD=12345 psql -d bookshop -f db/data.sql -U danden
script:
  - npm test
